//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Major_Shopping_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminTable
    {
        public int adminID { get; set; }
        public string adminUserName { get; set; }
        public string adminPassword { get; set; }
    }
}
