//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Major_Shopping_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack
    {
        public int userID { get; set; }
        public int productID { get; set; }
        public int feedBackID { get; set; }
        public string userName { get; set; }
        public string userMessage { get; set; }
    
        public virtual ProductDetail ProductDetail { get; set; }
        public virtual User User { get; set; }
    }
}
