//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Major_Shopping_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int userID { get; set; }
        public int orderID { get; set; }
        public System.DateTime orderDate { get; set; }
        public System.DateTime requiredDate { get; set; }
        public System.DateTime shippedDate { get; set; }
        public string shipName { get; set; }
        public string shipAddress { get; set; }
        public string shipCity { get; set; }
        public string shipState { get; set; }
        public string shipCountry { get; set; }
    
        public virtual OrderDetail OrderDetail { get; set; }
        public virtual User User { get; set; }
    }
}
